package de.fraunhofer.iese.cognac.ads.ads_platform.security;

import de.fraunhofer.iese.cognac.ads.ads_platform.constants.OAuthScopes;

public interface SecurityFilters {

  String _HAS_SCOPE_PREFIX = "hasAuthority('SCOPE_";
  String _HAS_SCOPE_SUFFIX = "')";

  String HAS_SCOPE_TWIN_HUB_TWINS_READ = _HAS_SCOPE_PREFIX + OAuthScopes.TWIN_HUB_TWINS_READ + _HAS_SCOPE_SUFFIX;
  String HAS_SCOPE_TWIN_HUB_TWINS_WRITE = _HAS_SCOPE_PREFIX + OAuthScopes.TWIN_HUB_TWINS_WRITE + _HAS_SCOPE_SUFFIX;
  String HAS_SCOPE_TWIN_HUB_TWINS_MANAGE = _HAS_SCOPE_PREFIX + OAuthScopes.TWIN_HUB_TWINS_MANAGE + _HAS_SCOPE_SUFFIX;

  String HAS_SCOPE_TWIN_HUB_DATA_SOVEREIGNTY_REQUEST_CONSENT = _HAS_SCOPE_PREFIX + OAuthScopes.TWIN_HUB_DATA_SOVEREIGNTY_REQUEST_CONSENT + _HAS_SCOPE_SUFFIX;
  String HAS_SCOPE_TWIN_HUB_DATA_SOVEREIGNTY_MANAGE = _HAS_SCOPE_PREFIX + OAuthScopes.TWIN_HUB_DATA_SOVEREIGNTY_MANAGE + _HAS_SCOPE_SUFFIX;

  String HAS_SCOPE_CONNECTOR_CONNECTOR_CREDENTIALS_MANAGE = _HAS_SCOPE_PREFIX + OAuthScopes.CONNECTOR_CONNECTOR_CREDENTIALS_MANAGE + _HAS_SCOPE_SUFFIX;

  String HAS_SCOPE_ML_HUB_LABELED_DATA_READ = _HAS_SCOPE_PREFIX + OAuthScopes.ML_HUB_LABELED_DATA_READ + _HAS_SCOPE_SUFFIX;
  String HAS_SCOPE_ML_HUB_LABELED_DATA_WRITE = _HAS_SCOPE_PREFIX + OAuthScopes.ML_HUB_LABELED_DATA_WRITE + _HAS_SCOPE_SUFFIX;
  String HAS_SCOPE_ML_HUB_ML_MODELS_READ = _HAS_SCOPE_PREFIX + OAuthScopes.ML_HUB_ML_MODELS_READ + _HAS_SCOPE_SUFFIX;
  String HAS_SCOPE_ML_HUB_ML_MODELS_WRITE = _HAS_SCOPE_PREFIX + OAuthScopes.ML_HUB_ML_MODELS_WRITE + _HAS_SCOPE_SUFFIX;

}
