package de.fraunhofer.iese.cognac.ads.ads_platform.twin_hub.data_sovereignty.dto;

public enum TwinResourceDto {
  TRACKS,
  ARABLE_AREA,
  TRAFFICABLE_AREA,
  NON_TRAFFICABLE_AREA,
  WORK_RECORDS_FERTILIZATION,
  WORK_RECORDS_WEED_CONTROL,
  WORK_RECORDS_SEEDING,
  WORK_RECORDS_HARVESTING,
  SOIL_MEASUREMENT_WORK_ORDERS,
  SOIL_MEASUREMENT_WORK_RECORDS,
  WORK_TIME_ESTIMATES,
  CROP_MATURITY_FORECASTS,
  RECOMMENDATIONS,
  SOIL_COMPOSITION_OBSERVATIONS,
  SOIL_NUTRIENTS_OBSERVATIONS,
  VEGETATION_INDEX_OBSERVATIONS,
  CROP_MATURITY_OBSERVATIONS,
  NITROGEN_OUTGASSING_OBSERVATIONS,
  DATA_FILES,
  PLANT_OBSERVATIONS,
}
